"""Platform-specific contest adapters for onboarding and submission."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


@dataclass
class ContestMetadata:
    """Parsed contest metadata."""

    id: str
    name: str
    platform: str
    repo_url: str
    scope_files: List[str] = field(default_factory=list)
    severity_criteria: Dict[str, str] = field(default_factory=dict)
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    max_payout: Optional[float] = None


class ContestAdapter(ABC):
    """Base adapter for contest platforms."""

    @property
    @abstractmethod
    def platform_name(self) -> str:
        pass

    @abstractmethod
    def onboard(self, contest_url: str) -> ContestMetadata:
        """Fetch contest metadata and clone repo."""
        pass

    @abstractmethod
    def parse_scope(self, repo_path: Path) -> List[str]:
        """Parse in-scope files from contest repo."""
        pass

    @abstractmethod
    def format_submission(
        self, finding: Dict, draft: bool = True
    ) -> str:
        """Format a finding for platform-specific submission."""
        pass


class Code4renaAdapter(ContestAdapter):
    """Adapter for Code4rena contests."""

    @property
    def platform_name(self) -> str:
        return "code4rena"

    def onboard(self, contest_url: str) -> ContestMetadata:
        # Extract contest ID from URL if possible
        import re
        match = re.search(r'code4rena\.com/[^/]+/([^/]+)', contest_url)
        contest_id = match.group(1) if match else "c4-unknown"
        
        return ContestMetadata(
            id=contest_id,
            name=f"Code4rena {contest_id}",
            platform="code4rena",
            repo_url=contest_url,
            severity_criteria={
                "high": "Direct loss of funds or permanent freeze",
                "medium": "Temporary freeze or value leakage",
                "low": "Informational or gas optimization",
            },
        )

    def parse_scope(self, repo_path: Path) -> List[str]:
        scope_file = repo_path / "scope.txt"
        if scope_file.exists():
            return scope_file.read_text().strip().splitlines()
        return []

    def format_submission(self, finding: Dict, draft: bool = True) -> str:
        lines = [
            f"# {finding.get('title', 'Finding')}",
            "",
            "## Severity",
            f"{finding.get('severity', 'Medium')}",
            "",
            "## Description",
            finding.get("description", ""),
            "",
            "## Impact",
            finding.get("impact", ""),
            "",
            "## Proof of Concept",
            finding.get("poc", ""),
            "",
            "## Recommended Mitigation",
            finding.get("mitigation", ""),
        ]
        if draft:
            lines.append("")
            lines.append("---")
            lines.append("*This is a DRAFT generated by VulnHunter. Review before submitting.*")
        return "\n".join(lines)


class SherlockAdapter(ContestAdapter):
    """Adapter for Sherlock contests."""

    @property
    def platform_name(self) -> str:
        return "sherlock"

    def onboard(self, contest_url: str) -> ContestMetadata:
        return ContestMetadata(
            id="sherlock-2024-01",
            name="Sample Sherlock Contest",
            platform="sherlock",
            repo_url=contest_url,
            severity_criteria={
                "high": "Direct loss of funds",
                "medium": "Value leakage or temporary freeze",
            },
        )

    def parse_scope(self, repo_path: Path) -> List[str]:
        readme = repo_path / "README.md"
        if readme.exists():
            # Simple parsing: look for markdown code blocks or file references
            text = readme.read_text()
            # This is a simplified parser
            return [line.strip() for line in text.splitlines() if line.strip().endswith(".sol")]
        return []

    def format_submission(self, finding: Dict, draft: bool = True) -> str:
        lines = [
            f"# {finding.get('title', 'Finding')}",
            "",
            "## Summary",
            finding.get("description", ""),
            "",
            "## Vulnerability Detail",
            finding.get("detail", ""),
            "",
            "## Impact",
            finding.get("impact", ""),
            "",
            "## Code Snippet",
            finding.get("code", ""),
            "",
            "## Tool used",
            "VulnHunter",
            "",
            "## Recommendation",
            finding.get("mitigation", ""),
        ]
        if draft:
            lines.append("")
            lines.append("---")
            lines.append("*DRAFT - Review required before submission.*")
        return "\n".join(lines)


class CantinaAdapter(ContestAdapter):
    """Adapter for Cantina contests."""

    @property
    def platform_name(self) -> str:
        return "cantina"

    def onboard(self, contest_url: str) -> ContestMetadata:
        return ContestMetadata(
            id="cantina-2024-01",
            name="Sample Cantina Contest",
            platform="cantina",
            repo_url=contest_url,
        )

    def parse_scope(self, repo_path: Path) -> List[str]:
        return []

    def format_submission(self, finding: Dict, draft: bool = True) -> str:
        return f"# {finding.get('title', 'Finding')}\n\n{finding.get('description', '')}"


class CodehawksAdapter(ContestAdapter):
    """Adapter for Codehawks contests."""

    @property
    def platform_name(self) -> str:
        return "codehawks"

    def onboard(self, contest_url: str) -> ContestMetadata:
        return ContestMetadata(
            id="codehawks-2024-01",
            name="Sample Codehawks Contest",
            platform="codehawks",
            repo_url=contest_url,
        )

    def parse_scope(self, repo_path: Path) -> List[str]:
        return []

    def format_submission(self, finding: Dict, draft: bool = True) -> str:
        return f"# {finding.get('title', 'Finding')}\n\n{finding.get('description', '')}"
