"""PoC command - Proof of Concept generation."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel

from vulnhunter.llm import OrchestratorBrain
from vulnhunter.recon.models import ReconReport

app = typer.Typer(
    name="poc",
    help="🎯 Generate Proof-of-Concept exploits",
    rich_markup_mode="rich",
)
console = Console()


@app.command()
def generate(
    recon_file: Path = typer.Argument(..., help="Path to recon report"),
    finding_file: Path = typer.Argument(..., help="Path to finding JSON"),
    output: Path = typer.Option(
        ...,
        "--output",
        "-o",
        help="Output directory for PoC files",
    ),
    template: Optional[str] = typer.Option(
        None,
        "--template",
        "-t",
        help="PoC template to use",
    ),
):
    """Generate a PoC exploit for a vulnerability.

    Uses the recon context and finding details to generate a
    working Foundry test that demonstrates the vulnerability.
    """
    console.print(f"[bold blue]🎯 Generating PoC[/bold blue]")

    # Load files
    recon_report = ReconReport.model_validate_json(recon_file.read_text())
    finding = json.loads(finding_file.read_text())

    # Initialize orchestrator
    brain = OrchestratorBrain()

    # Check if PoC should be generated
    if not brain.should_generate_poc(finding):
        console.print("[yellow]⚠️  Finding does not meet PoC generation criteria[/yellow]")
        console.print("Need: High/Critical severity with Medium/High confidence")
        raise typer.Exit(1)

    # Generate PoC (placeholder - full implementation would use LLM)
    console.print(f"\nFinding: {finding.get('title', 'Unknown')}")
    console.print(f"Severity: {finding.get('severity', 'Unknown')}")
    console.print(f"Contract: {finding.get('contract', 'Unknown')}")

    # Create output directory
    output.mkdir(parents=True, exist_ok=True)

    # Generate basic PoC structure
    poc_content = generate_poc_template(finding, recon_report)

    # Save PoC
    poc_file = output / f"POC_{finding.get('id', 'vuln')}.t.sol"
    poc_file.write_text(poc_content)

    console.print(f"\n[green]✓ PoC generated: {poc_file}[/green]")

    # Show preview
    console.print(
        Panel(
            poc_content[:500] + "..." if len(poc_content) > 500 else poc_content,
            title="PoC Preview",
            border_style="blue",
        )
    )


@app.command()
def batch(
    recon_file: Path = typer.Argument(..., help="Path to recon report"),
    findings_file: Path = typer.Argument(..., help="Path to findings JSON array"),
    output: Path = typer.Option(
        ...,
        "--output",
        "-o",
        help="Output directory for PoC files",
    ),
):
    """Generate PoCs for all qualifying findings.

    Automatically filters findings and generates PoCs only for
    high-confidence, high-severity vulnerabilities.
    """
    console.print(f"[bold blue]🎯 Batch PoC generation[/bold blue]")

    # Load files
    recon_report = ReconReport.model_validate_json(recon_file.read_text())
    findings = json.loads(findings_file.read_text())

    # Initialize orchestrator
    brain = OrchestratorBrain()

    # Filter findings for PoC generation
    qualifying = [f for f in findings if brain.should_generate_poc(f)]

    console.print(f"Found {len(findings)} total findings")
    console.print(f"Qualifying for PoC: {len(qualifying)}")

    if not qualifying:
        console.print("[yellow]No findings qualify for PoC generation[/yellow]")
        raise typer.Exit(0)

    # Create output directory
    output.mkdir(parents=True, exist_ok=True)

    # Generate PoCs
    generated = []
    for finding in qualifying:
        poc_content = generate_poc_template(finding, recon_report)
        poc_file = output / f"POC_{finding.get('id', 'vuln')}.t.sol"
        poc_file.write_text(poc_content)
        generated.append(poc_file.name)

    console.print(f"\n[green]✓ Generated {len(generated)} PoC files:[/green]")
    for name in generated:
        console.print(f"  - {name}")


def generate_poc_template(finding: dict, recon: ReconReport) -> str:
    """Generate a basic PoC template."""
    contract = finding.get("contract", "Target")
    vuln_type = finding.get("type", "Vulnerability")

    return f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

/// @title PoC: {vuln_type}
/// @notice Generated by VulnHunter
contract POC_{finding.get("id", "Vuln")} is Test {{
    // Target contract
    {contract} public target;

    // Fork configuration
    uint256 public mainnetFork;
    uint256 public constant BLOCK_NUMBER = 18_000_000;

    function setUp() public {{
        // Create fork
        mainnetFork = vm.createFork("mainnet", BLOCK_NUMBER);
        vm.selectFork(mainnetFork);

        // Deploy target (or use existing address)
        // target = {contract}(0x...);
    }}

    /// @notice PoC for {vuln_type}
    /// {finding.get("description", "No description")}
    function testExploit() public {{
        // Setup
        vm.deal(address(this), 100 ether);

        // Execute attack
        // TODO: Implement exploit steps

        // Verify impact
        // TODO: Add assertions
    }}

    /// @notice Test mitigation
    function testMitigation() public {{
        // TODO: Verify fix works
    }}
}}
"""
