"""CVL (Certora Verification Language) spec generator.

Takes invariant candidates and generates .spec files for Certora Prover.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


class CVLGenerator:
    """Generates CVL .spec files from invariant candidates."""

    def __init__(self, model: str = "claude-opus-4"):
        self.model = model

    def generate_spec(
        self,
        contract_name: str,
        invariants: List[str],
        contract_source: str,
        output_dir: Optional[Path] = None,
    ) -> Path:
        """Generate a CVL spec file for the given contract and invariants.

        Args:
            contract_name: Name of the contract (e.g., "MyToken")
            invariants: List of invariant descriptions in natural language
            contract_source: Solidity source code for context
            output_dir: Directory to write the spec file (default: certora/specs/)

        Returns:
            Path to the generated .spec file
        """
        output_dir = output_dir or Path("certora/specs")
        output_dir.mkdir(parents=True, exist_ok=True)

        spec_path = output_dir / f"{contract_name}.spec"

        # Build the spec file
        lines = [
            f"// CVL spec for {contract_name}",
            "// Auto-generated by VulnHunter",
            "",
            f'using {contract_name} as {contract_name};',
            "",
            "// Ghost variables for tracking state",
            "ghost mathint ghost_sumOfBalances {",
            "    init_state axiom ghost_sumOfBalances == 0;",
            "}",
            "",
            "// Hooks for tracking balance changes",
            "hook Sstore _balances[KEY address user] uint256 newBalance (uint256 oldBalance) {",
            "    ghost_sumOfBalances = ghost_sumOfBalances - oldBalance + newBalance;",
            "}",
            "",
        ]

        # Add invariants
        for i, invariant in enumerate(invariants, 1):
            lines.extend([
                f"// Invariant {i}: {invariant}",
                f"invariant {self._sanitize_name(invariant)}()",
                "    // NOTE: This invariant template requires human verification",
                "    // The LLM has identified this as a candidate invariant",
                "    // Review the contract logic and refine before running Certora",
                "    true;",
                "",
            ])

        # Add methods block
        lines.extend([
            "methods {",
            "    // Define methods that should be checked",
            "    function totalSupply() external returns uint256 envfree;",
            "    function balanceOf(address) external returns uint256 envfree;",
            "}",
            "",
        ])

        spec_content = "\n".join(lines)
        spec_path.write_text(spec_content)

        logger.info(f"Generated CVL spec: {spec_path}")
        return spec_path

    def generate_config(
        self,
        contract_file: Path,
        contract_name: str,
        spec_file: Path,
        output_dir: Optional[Path] = None,
    ) -> Path:
        """Generate a Certora config file (.conf).

        Args:
            contract_file: Path to the Solidity contract
            contract_name: Name of the contract
            spec_file: Path to the .spec file
            output_dir: Directory to write the config file

        Returns:
            Path to the generated .conf file
        """
        output_dir = output_dir or Path("certora")
        output_dir.mkdir(parents=True, exist_ok=True)

        config_path = output_dir / f"{contract_name}.conf"

        import json
        config = {
            "files": [str(contract_file)],
            "verify": f"{contract_name}:{spec_file}",
            "solc": "solc8.20",
            "optimistic_loop": True,
            "rule_sanity": "basic",
            "send_only": True,
        }

        config_path.write_text(json.dumps(config, indent=2))
        logger.info(f"Generated Certora config: {config_path}")
        return config_path

    def _sanitize_name(self, text: str) -> str:
        """Convert natural language to a valid CVL identifier."""
        # Remove special characters, keep alphanumeric and underscores
        sanitized = "".join(c if c.isalnum() else "_" for c in text)
        # Remove consecutive underscores
        while "__" in sanitized:
            sanitized = sanitized.replace("__", "_")
        # Trim and ensure it starts with a letter
        sanitized = sanitized.strip("_")
        if sanitized and sanitized[0].isdigit():
            sanitized = "inv_" + sanitized
        return sanitized or "invariant"
